apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaf-chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaf-chat-service
  template:
    metadata:
      labels:
        app: leaf-chat-service
    spec:
      containers:
        - name: leaf-chat-service
          image: sriraghariharan/leaf-chat-service:v2
          ports:
            - containerPort: 2004
          envFrom:
            - configMapRef:
                name: leaf-chat-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: leaf-chat-service
spec:
  type: ClusterIP
  selector:
    app: leaf-chat-service
  ports:
    - protocol: TCP
      port: 2004
      targetPort: 2004
